# Generated by Django 4.2.23 on 2026-06-16 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_participant_treatment_arm'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='google_access_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='google_refresh_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='google_token_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
