# Generated by Django 4.2.23 on 2026-07-27 17:45

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_participant_google_access_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='google_access_token',
            field=core.fields.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='google_refresh_token',
            field=core.fields.EncryptedTextField(blank=True, null=True),
        ),
    ]
