# Generated by Django 4.2.23 on 2026-07-27 18:09

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_encrypt_existing_google_tokens'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='backup_email',
            field=core.fields.EncryptedTextField(blank=True, null=True),
        ),
    ]
