# Generated by Django 4.2.23 on 2026-07-29 13:26

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_participant_backup_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='backup_email',
        ),
        migrations.AddField(
            model_name='customuser',
            name='backup_email',
            field=core.fields.EncryptedTextField(blank=True, null=True),
        ),
    ]
