# Generated by Django 4.2.23 on 2026-08-03 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_participant_backup_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='google_oauth_state',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='google_oauth_state_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
