# Generated by Django 4.2.30 on 2026-08-04 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_null_existing_fitbit_tokens'),
    ]

    operations = [
        # The trigger from migration 0006 references OLD/NEW.fitbit_refresh_token
        # directly in its function body. Postgres doesn't validate that reference
        # until the trigger actually fires, so it must be dropped before the
        # column, or every subsequent UPDATE on core_participant breaks.
        migrations.RunSQL(
            sql="""
                DROP TRIGGER IF EXISTS fitbit_token_history_trigger ON core_participant;
                DROP FUNCTION IF EXISTS log_fitbit_token_changes();
                DROP TABLE IF EXISTS core_participant_fitbit_token_history;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RemoveField(
            model_name='participant',
            name='fitbit_access_token',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='fitbit_auth_token',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='fitbit_refresh_token',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='fitbit_token_expires',
        ),
    ]
