# Generated by Django 5.2.17 on 2026-08-27 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_participant_fitbit_access_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='must_change_password',
            field=models.BooleanField(default=False, help_text='If set, the user is forced to change their password before doing anything else.'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='password_expires_at',
            field=models.DateTimeField(blank=True, help_text='If must_change_password is True and this time has passed, the temporary password is no longer valid.', null=True),
        ),
    ]
