# core/forms.py
import secrets
from datetime import timedelta

from django import forms
from django.contrib.auth import password_validation
from django.contrib.auth.forms import ReadOnlyPasswordHashField
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
from .models import CustomUser

class CustomUserCreationForm(forms.ModelForm):
    """
    A form for creating new users. The initial password is generated by the
    system, never chosen by the admin, and must be changed on first login.
    """
    backup_email = forms.EmailField(required=False, label="Backup Email (optional)")

    class Meta:
        model = CustomUser
        fields = ('email', 'backup_email')

    def save(self, commit=True):
        user = super().save(commit=False)
        if user.is_staff:
            self.generated_password = secrets.token_urlsafe(12)
            user.set_password(self.generated_password)
            user.must_change_password = True
            user.password_expires_at = timezone.now() + timedelta(hours=48)
        else:
            # Participants never log in to this app — no usable credential needed.
            user.set_unusable_password()
        if commit:
            user.save()
        return user
        
class CustomUserChangeForm(forms.ModelForm):
    """
    A form for updating users. Includes all the fields on
    the user, but replaces the password field with admin's
    password hash display field.
    """
    password = ReadOnlyPasswordHashField(
        label=_("Password"),
        help_text=_(
            'Raw passwords are not stored, so there is no way to see this '
            'user\'s password, but you can change the password using '
            '<a href="../password/">this form</a>.'
        ),
    )
    backup_email = forms.EmailField(required=False, label="Backup Email (optional)")
    
    class Meta:
        model = CustomUser
        fields = ('email', 'password', 'backup_email', 'is_active', 'is_staff', 'is_superuser')